## 代码2-1 创建数组并查看数组属性

In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4])

In [3]:
print("创建的数组为：",arr1)

创建的数组为： [1 2 3 4]


In [4]:
arr2 = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])

In [5]:
print(arr2)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [6]:
arr2.shape

(3, 4)

In [7]:
arr1.shape

(4,)

In [8]:
arr2.dtype

dtype('int32')

In [9]:
arr2.size

12

In [10]:
arr2.itemsize

4

## 代码2-2 重新设置数组的shape属性

In [11]:
arr2.shape = 4,3

In [12]:
print(arr2)

[[ 1  2  3]
 [ 4  4  5]
 [ 6  7  7]
 [ 8  9 10]]


代码2-3 使用arange函数创建数组

In [13]:
arr3 = np.arange(0,1,0.1)

In [14]:
arr3

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

## 2-4 使用linspace函数创建数组

In [15]:
np.linspace(0,1,12)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

## 2-5 使用logspace创建数组

In [16]:
np.logspace(0,1,20)

array([ 1.        ,  1.12883789,  1.27427499,  1.43844989,  1.62377674,
        1.83298071,  2.06913808,  2.33572147,  2.6366509 ,  2.97635144,
        3.35981829,  3.79269019,  4.2813324 ,  4.83293024,  5.45559478,
        6.15848211,  6.95192796,  7.8475997 ,  8.8586679 , 10.        ])

## 2-6 使用zero 函数创建数组

In [17]:
arr4 = np.zeros((2,3))

In [18]:
arr4

array([[0., 0., 0.],
       [0., 0., 0.]])

## 2-7 使用eye 函数创建数组

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 2-8 使用diag 函数创建数组

In [20]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

## 2-9 使用ones 函数创建数组


In [21]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## 2-10数组的数据类型转换

In [22]:
np.float64(42)

42.0

In [23]:
np.int8(42.0)

42

In [24]:
print(np.bool_(42))

True


In [25]:
print(np.bool_(0))

False


In [26]:
print(np.float_(True))

1.0


In [27]:
print(np.float_(False))

0.0


## 2-11 创建数据类型

In [28]:
df = np.dtype([('name',np.str_,40),('numitems',np.int64),('price',np.float64)])

In [29]:
print('数据类型为：\n',df)

数据类型为：
 [('name', '<U40'), ('numitems', '<i8'), ('price', '<f8')]


## 2-12 查看数据类型

In [30]:
print('数据类型为：', df['name'])

数据类型为： <U40


In [31]:
print('数据类型为：', np.dtype(df['name']))

数据类型为： <U40


## 2-13 自定义数据类型

In [32]:
itemz = np.array([('tomatoes', 42, 4.14),('cabbages',13,1.72)],dtype=df)

In [33]:
print('自定义数据为:',itemz)

自定义数据为: [('tomatoes', 42, 4.14) ('cabbages', 13, 1.72)]


## 2-14 使用random 函数生成随机数

In [34]:
print('生成的随机数为: \n', np.random.random(100))

生成的随机数为: 
 [0.12924488 0.42500365 0.2358468  0.01017612 0.23745165 0.51919865
 0.66827686 0.38081375 0.6389195  0.72106575 0.30938302 0.43893605
 0.81586767 0.18153956 0.89688655 0.95251298 0.90041798 0.29512883
 0.11442889 0.58557171 0.9964393  0.91747883 0.23802336 0.79120316
 0.76250789 0.52794084 0.01512664 0.50269588 0.19671698 0.90751949
 0.94139549 0.51001785 0.73796927 0.32196386 0.67517685 0.4716836
 0.74061042 0.73854793 0.79243337 0.65877032 0.33614669 0.40065419
 0.82707395 0.86315545 0.25973792 0.73984722 0.25162553 0.73523415
 0.90857504 0.17930786 0.08867392 0.13227536 0.82708047 0.64530181
 0.2060498  0.30260826 0.48672975 0.59277547 0.77982694 0.88138474
 0.81232666 0.23562836 0.12158814 0.23697797 0.55733725 0.11230857
 0.69953366 0.39113326 0.6812235  0.3685306  0.01350427 0.58350105
 0.73521521 0.76784101 0.62452481 0.60845198 0.48795263 0.61584814
 0.05716889 0.56736896 0.55343496 0.36417197 0.86852982 0.98576672
 0.10085893 0.52064385 0.26683643 0.93402594 0.99147

## 2-15 使用rand 函数生成服从均匀分布的随机数

In [35]:
np.random.rand(10,5)

array([[0.91850125, 0.72492815, 0.94228332, 0.26311252, 0.24270647],
       [0.30598039, 0.74570546, 0.44538764, 0.66037151, 0.82511203],
       [0.64444981, 0.60957024, 0.99483942, 0.66328558, 0.56783057],
       [0.0848871 , 0.36207528, 0.38884996, 0.82022352, 0.81519252],
       [0.815675  , 0.04739186, 0.53447233, 0.7968234 , 0.12079276],
       [0.83574162, 0.46314789, 0.19003784, 0.19248346, 0.12421431],
       [0.05148905, 0.74936158, 0.41921131, 0.16734262, 0.98532577],
       [0.12206622, 0.87302276, 0.6555522 , 0.91634665, 0.94429915],
       [0.18886292, 0.21186503, 0.33230039, 0.94345054, 0.29250142],
       [0.89736164, 0.73126134, 0.95324428, 0.55509311, 0.77622429]])

## 2-16 使用rand函数生成服从正态分布的随机数

In [36]:
np.random.randn(10,5)

array([[ 1.14389356, -1.37520694,  0.97735453, -1.46760214,  1.42470423],
       [ 1.11219798, -0.11509096,  0.30415369,  0.65388946, -0.52359293],
       [-0.63702382, -0.44881937, -1.52389044, -0.68823002, -1.36141154],
       [ 0.32455397, -1.3746883 ,  0.16044139,  1.71194211,  0.41957053],
       [-0.33098301, -0.0182576 ,  1.14253214, -0.16108905,  0.64326116],
       [ 0.17245998,  0.76747058, -0.74440631, -0.13549252, -0.69379448],
       [-1.10678127,  0.03221781, -0.53645785,  1.10288715,  0.55186701],
       [ 0.95128758,  0.5553214 ,  1.99727095,  0.90469719,  2.62355635],
       [ 1.06405642,  0.73328734,  0.02598015, -0.64565657, -1.20254134],
       [-0.5967631 ,  2.24529481,  0.90879528, -0.8687447 ,  3.31202538]])

## 2-17 使用randit 函数生成指定范围的随机数

In [37]:
np.random.randint(2, 10, size=[2, 5])

array([[5, 9, 6, 5, 2],
       [8, 4, 6, 2, 6]])

## 2-18 使用索引访问一维数组

In [38]:
arr = np.arange(10)

In [39]:
print(arr[5])

5


In [40]:
print(arr[3:5])

[3 4]


In [41]:
print(arr[:5])

[0 1 2 3 4]


In [42]:
print(arr[-1])

9


In [43]:
arr[2:4] = 100,101

In [44]:
print(arr)

[  0   1 100 101   4   5   6   7   8   9]


In [45]:
print(arr[1:-1:2])

[  1 101   5   7]


In [46]:
print(arr[5:1:-2])

[  5 101]


## 2-19 使用索引访问多维数组


In [47]:
arr = np.array([[1, 2, 3, 4, 5] , [4, 5, 6, 7, 8] , [7, 8, 9, 10, 11]])

In [48]:
print(arr)

[[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]]


In [49]:
print(arr[0, 3:5])

[4 5]


In [50]:
print(arr[1:,2:])

[[ 6  7  8]
 [ 9 10 11]]


In [51]:
print(arr[:,2])

[3 6 9]


## 2-20 使用整数序列索引和布尔值索引访问多维数组

In [52]:
print(arr[tuple([(0, 1, 2),(1, 2, 3)])])

[ 2  6 10]


In [53]:
print(arr[1:,(0, 2, 3)])

[[ 4  6  7]
 [ 7  9 10]]


In [54]:
mask = np.array([1, 0, 1], dtype = np.bool_)
print(arr[mask,2])

[3 9]


## 2-21 改变数组形状

In [55]:
arr = np.arange(12)

In [56]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [57]:
print(arr.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [58]:
print('数组维度为: ',arr.reshape(3,4).ndim)

数组维度为:  2


## 2-22 使用ravel 函数展平数组


In [59]:
arr = np.arange(12).reshape(3,4)

In [60]:
print('创建的二维数组为：\n',arr)

创建的二维数组为：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [61]:
print('数组展平为：',arr.ravel())

数组展平为： [ 0  1  2  3  4  5  6  7  8  9 10 11]


## 2-23 使用flatten 函数展平数组

In [62]:
print(arr.flatten()) #横向展平

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [63]:
print(arr.flatten('F')) #纵向展平

[ 0  4  8  1  5  9  2  6 10  3  7 11]


## 2-24 使用hstack 函数实现数组横向组合

In [64]:
arr1 = np.arange(12).reshape(3,4)

In [65]:
print('创建的数组arr1为：\n',arr1)

创建的数组arr1为：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [66]:
arr2 = arr1 * 3

In [67]:
print('创建的数组arr2为: \n',arr2)

创建的数组arr2为: 
 [[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


In [68]:
print('横向组合后的数组为： \n',np.hstack((arr1,arr2)))

横向组合后的数组为： 
 [[ 0  1  2  3  0  3  6  9]
 [ 4  5  6  7 12 15 18 21]
 [ 8  9 10 11 24 27 30 33]]


## 2-25 使用vstack 函数实现数组纵向组合

In [69]:
print(np.vstack((arr1,arr2)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


## 2-26 使用concatenate 函数组合数组

In [70]:
print('横向组合后的数组为: \n',np.concatenate((arr1,arr2) , axis = 1))

横向组合后的数组为: 
 [[ 0  1  2  3  0  3  6  9]
 [ 4  5  6  7 12 15 18 21]
 [ 8  9 10 11 24 27 30 33]]


In [71]:
print('纵向组合后的数组为: \n', np.concatenate((arr1,arr2), axis = 0))

纵向组合后的数组为: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


## 2-27 使用hsplit 函数实现数组横向分割

In [72]:
arr = np.arange(16).reshape(4,4)

In [73]:
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [74]:
print('横向分割后的数组为: \n', np.hsplit(arr,2))

横向分割后的数组为: 
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


## 2-28 使用vsplit函数实现数组纵向分割


In [75]:
print('纵向分割后的数组为： \n', np.vsplit(arr,2))

纵向分割后的数组为： 
 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


## 2-29使用split 分割数组

In [76]:
print('横向分割后的数组： \n', np.split(arr, 2, axis = 1))

横向分割后的数组： 
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [77]:
print('纵向分割后的数组为： \n', np.split(arr, 2, axis = 0))

纵向分割后的数组为： 
 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
